services:
  app:
    build: ./.docker/php
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html

  db:
    image: jacobalberty/firebird:3.0
    environment:
      ISC_PASSWORD: masterkey
    ports:
      - "3050:3050"
    volumes:
      - ./data:/firebird/data